SalonZaAutomobile/Models/SalonAutomobila.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SalonZaAutomobile.Models
{
    public class SalonAutomobila
    {
        public int Id { get; set; }

        //[RegularExpression(@"\D{6}\")]
        public int Pib { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Naziv salona")]
        public string Naziv { get; set; }

        [Required]
        [StringLength(20)]
        public string Drzava { get; set; }

        [Required]
        [StringLength(20)]
        public string Grad { get; set; }

        [Required]
        [StringLength(20)]
        public string Adresa { get; set; }
        public List<Automobil> AutomobiliSalona { get; set; }
        public List<Ugovor> UgovoriSalona { get; set; }
    }
}

SalonZaAutomobile/Controllers/AutomobilsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SalonZaAutomobile.Models;

namespace SalonZaAutomobile.Controllers
{
    public class AutomobilsController : Controller
    {
        private SalonAutomobilaContext db = new SalonAutomobilaContext();

        // GET: Automobils
        public ActionResult Index()
        {
            var automobils = db.Automobils.Include(a => a.Proizvodjac).Include(a => a.SalonAutomobila);
            return View(automobils.ToList());
        }

        // GET: Automobils/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Automobil automobil = db.Automobils.Include(a => a.Proizvodjac).Include(a => a.SalonAutomobila).SingleOrDefault(x => x.Id == id);

            //Automobil automobil = automobils.Find(id);
            if (automobil == null)
            {
                return HttpNotFound();
            }
            return View(automobil);
        }
         
        // GET: Automobils/Create
        public ActionResult Create(int? id)
        {
            
            if (id != null)
            {
                SalonAutomobila s = db.SalonAutomobilas.Find(id);
                List<SalonAutomobila> salon = new List<SalonAutomobila>();
                salon.Add(s);
                ViewBag.SalonAutomobilaId = new SelectList(salon, "Id", "Naziv");

                List<Proizvodjac> sviproizvodjaci = db.Proizvodjacs.ToList();
                List<Ugovor> sviugovori = db.Ugovors.ToList();
                List<Proizvodjac> proizvodjacisalona = new List<Proizvodjac>();
                foreach (Proizvodjac p in sviproizvodjaci)
                {
                    foreach (Ugovor u in sviugovori)
                    {
                        if (p.Id==u.ProizvodjacId && u.SalonAutomobilaId==id)
                        {
                            proizvodjacisalona.Add(p);
                        }
                    }
                }
                ViewBag.ProizvodjacId = new SelectList(proizvodjacisalona, "Id", "Naziv");
            }
            else
            {
                ViewBag.ProizvodjacId = new SelectList(db.Proizvodjacs, "Id", "Naziv");
                ViewBag.SalonAutomobilaId = new SelectList(db.SalonAutomobilas, "Id", "Naziv");
            }
            return View();
        }

        // POST: Automobils/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Model,GodinaProizvodnje,Kubikaza,Boja,ProizvodjacId,SalonAutomobilaId")] Automobil automobil)
        {
            if (ModelState.IsValid)
            {
                db.Automobils.Add(automobil);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProizvodjacId = new SelectList(db.Proizvodjacs, "Id", "Naziv", automobil.ProizvodjacId);
            ViewBag.SalonAutomobilaId = new SelectList(db.SalonAutomobilas, "Id", "Naziv", automobil.SalonAutomobilaId);
            return View(automobil);
        }

        // GET: Automobils/Edit/5
        public ActionResult Edit(int? id, int? sid)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Automobil automobil = db.Automobils.Find(id);
            if (automobil == null)
            {
                return HttpNotFound();
            }

            if (sid != null)
            {
                SalonAutomobila s = db.SalonAutomobilas.Find(sid);
                List<SalonAutomobila> salon = new List<SalonAutomobila>();
                salon.Add(s);
                ViewBag.SalonAutomobilaId = new SelectList(salon, "Id", "Naziv");

                List<Proizvodjac> sviproizvodjaci = db.Proizvodjacs.ToList();
                List<Ugovor> sviugovori = db.Ugovors.ToList();
                List<Proizvodjac> proizvodjacisalona = new List<Proizvodjac>();
                foreach (Proizvodjac p in sviproizvodjaci)
                {
                    foreach (Ugovor u in sviugovori)
                    {
                        if (p.Id == u.ProizvodjacId && u.SalonAutomobilaId == sid)
                        {
                            proizvodjacisalona.Add(p);
                        }
                    }
                }
                ViewBag.ProizvodjacId = new SelectList(proizvodjacisalona, "Id", "Naziv");
            }
            else
            {
                ViewBag.ProizvodjacId = new SelectList(db.Proizvodjacs, "Id", "Naziv");
                ViewBag.SalonAutomobilaId = new SelectList(db.SalonAutomobilas, "Id", "Naziv");
            }
            return View(automobil);
        }

        // POST: Automobils/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Model,GodinaProizvodnje,Kubikaza,Boja,ProizvodjacId,SalonAutomobilaId")] Automobil automobil)
        {
            if (ModelState.IsValid)
            {
                db.Entry(automobil).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProizvodjacId = new SelectList(db.Proizvodjacs, "Id", "Naziv", automobil.ProizvodjacId);
            ViewBag.SalonAutomobilaId = new SelectList(db.SalonAutomobilas, "Id", "Naziv", automobil.SalonAutomobilaId);
            return View(automobil);
        }

        // GET: Automobils/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Automobil automobil = db.Automobils.Include(a => a.Proizvodjac).Include(a => a.SalonAutomobila).SingleOrDefault(x => x.Id == id);

            if (automobil == null)
            {
                return HttpNotFound();
            }
            return View(automobil);
        }

        // POST: Automobils/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Automobil automobil = db.Automobils.Find(id);
            db.Automobils.Remove(automobil);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SalonZaAutomobile/Controllers/SalonAutomobilasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SalonZaAutomobile.Models;

namespace SalonZaAutomobile.Controllers
{
    public class SalonAutomobilasController : Controller
    {
        private SalonAutomobilaContext db = new SalonAutomobilaContext();

        // GET: SalonAutomobilas
        public ActionResult Index()
        {
            return View(db.SalonAutomobilas.ToList());
        }

        // GET: SalonAutomobilas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SalonAutomobila salonAutomobila = db.SalonAutomobilas.Find(id);
            if (salonAutomobila == null)
            {
                return HttpNotFound();
            }

            var automobils = db.Automobils.Include(a => a.Proizvodjac).Include(a => a.SalonAutomobila).ToList();
            var ugovors = db.Ugovors.Include(u => u.Proizvodjac).Include(u => u.SalonAutomobila).ToList();


            return View(salonAutomobila);
        }

        // GET: SalonAutomobilas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SalonAutomobilas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Pib,Naziv,Drzava,Grad,Adresa")] SalonAutomobila salonAutomobila)
        {
            if (ModelState.IsValid)
            {
                db.SalonAutomobilas.Add(salonAutomobila);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(salonAutomobila);
        }

        // GET: SalonAutomobilas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SalonAutomobila salonAutomobila = db.SalonAutomobilas.Find(id);
            if (salonAutomobila == null)
            {
                return HttpNotFound();
            }
            return View(salonAutomobila);
        }

        // POST: SalonAutomobilas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Pib,Naziv,Drzava,Grad,Adresa")] SalonAutomobila salonAutomobila)
        {
            if (ModelState.IsValid)
            {
                db.Entry(salonAutomobila).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(salonAutomobila);
        }

        // GET: SalonAutomobilas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SalonAutomobila salonAutomobila = db.SalonAutomobilas.Find(id);
            if (salonAutomobila == null)
            {
                return HttpNotFound();
            }
            return View(salonAutomobila);
        }

        // POST: SalonAutomobilas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SalonAutomobila salonAutomobila = db.SalonAutomobilas.Find(id);
            db.SalonAutomobilas.Remove(salonAutomobila);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SalonZaAutomobile/Controllers/UgovorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SalonZaAutomobile.Models;

namespace SalonZaAutomobile.Controllers
{
    public class UgovorsController : Controller
    {
        private SalonAutomobilaContext db = new SalonAutomobilaContext();

        // GET: Ugovors
        public ActionResult Index()
        {
            var ugovors = db.Ugovors.Include(u => u.Proizvodjac).Include(u => u.SalonAutomobila);
            return View(ugovors.ToList());
        }

        // GET: Ugovors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ugovor ugovor = db.Ugovors.Include(u => u.Proizvodjac).Include(u => u.SalonAutomobila).SingleOrDefault(x => x.Id == id);
            if (ugovor == null)
            {
                return HttpNotFound();
            }
            return View(ugovor);
        }

        // GET: Ugovors/Create
        public ActionResult Create(int? id)
        {
            if (id != null)
            {
                SalonAutomobila s = db.SalonAutomobilas.Find(id);
                List<SalonAutomobila> salon = new List<SalonAutomobila>();
                salon.Add(s);
                ViewBag.SalonAutomobilaId = new SelectList(salon, "Id", "Naziv");  
            }
            else
            {
                ViewBag.SalonAutomobilaId = new SelectList(db.SalonAutomobilas, "Id", "Naziv");
            }

            ViewBag.ProizvodjacId = new SelectList(db.Proizvodjacs, "Id", "Naziv");

            return View();
        }

        // POST: Ugovors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,SalonAutomobilaId,ProizvodjacId")] Ugovor ugovor)
        {
            if (ModelState.IsValid)
            {
                db.Ugovors.Add(ugovor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProizvodjacId = new SelectList(db.Proizvodjacs, "Id", "Naziv", ugovor.ProizvodjacId);
            ViewBag.SalonAutomobilaId = new SelectList(db.SalonAutomobilas, "Id", "Naziv", ugovor.SalonAutomobilaId);
            return View(ugovor);
        }

        // GET: Ugovors/Edit/5
        public ActionResult Edit(int? id, int? sid)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ugovor ugovor = db.Ugovors.Find(id);
            if (ugovor == null)
            {
                return HttpNotFound();
            }
            if (sid != null)
            {
                SalonAutomobila s = db.SalonAutomobilas.Find(sid);
                List<SalonAutomobila> salon = new List<SalonAutomobila>();
                salon.Add(s);
                ViewBag.SalonAutomobilaId = new SelectList(salon, "Id", "Naziv");
            }
            else
            {
                ViewBag.SalonAutomobilaId = new SelectList(db.SalonAutomobilas, "Id", "Naziv");
            }

            ViewBag.ProizvodjacId = new SelectList(db.Proizvodjacs, "Id", "Naziv", ugovor.ProizvodjacId);
;
            return View(ugovor);
        }

        // POST: Ugovors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SalonAutomobilaId,ProizvodjacId")] Ugovor ugovor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ugovor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProizvodjacId = new SelectList(db.Proizvodjacs, "Id", "Naziv", ugovor.ProizvodjacId);
            ViewBag.SalonAutomobilaId = new SelectList(db.SalonAutomobilas, "Id", "Naziv", ugovor.SalonAutomobilaId);
            return View(ugovor);
        }

        // GET: Ugovors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ugovor ugovor = db.Ugovors.Include(u => u.Proizvodjac).Include(u => u.SalonAutomobila).SingleOrDefault(x => x.Id == id);
            if (ugovor == null)
            {
                return HttpNotFound();
            }
            return View(ugovor);
        }

        // POST: Ugovors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ugovor ugovor = db.Ugovors.Find(id);
            db.Ugovors.Remove(ugovor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SalonZaAutomobile/Views/SalonAutomobilas/Create.cshtml
@model SalonZaAutomobile.Models.SalonAutomobila

@{
    ViewBag.Title = "Kreiraj";
}

<h2>Kreiraj</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SalonAutomobila</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Pib, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pib, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pib, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Drzava, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Drzava, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Drzava, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Povratak na početnu stranicu", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SalonZaAutomobile/Views/SalonAutomobilas/Delete.cshtml
@model SalonZaAutomobile.Models.SalonAutomobila

@{
    ViewBag.Title = "Obriši";
}

<h2>DObriši</h2>

<h3>Da li ste sigurni da želite da obrišete ovo?</h3>
<div>
    <h4>SalonAutomobila</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pib)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pib)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Drzava)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Drzava)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adresa)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>
<p>@Html.ActionLink("Povratak na glavni meni", "Index", "SalonAutomobilas")</p>

SalonZaAutomobile/Views/SalonAutomobilas/Details.cshtml
@model SalonZaAutomobile.Models.SalonAutomobila

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SalonAutomobila</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pib)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pib)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Drzava)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Drzava)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adresa)
        </dd>

    </dl>
</div>
<hr />
<div>
    <p>
        <a href="/Automobils/Create?id=@Model.Id">Kreiraj novi automobil</a>
    </p>
    <h2>Automobili salona</h2>
    <table class="table">
        <tr>
            <th>
                Proizvođač
            </th>
            <th>
                Salon
            </th>
            <th>
                Model
            </th>
            <th>
                Godina Proizvodnje
            </th>
            <th>
                Kubikaža
            </th>
            <th>
                @* @Html.DisplayNameFor(model => model.AutomobiliSalona.Boja)*@
                Boja
            </th>
            <th></th>
        </tr>

        @if (Model.AutomobiliSalona != null)
        {
            foreach (var item in Model.AutomobiliSalona)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Proizvodjac.Naziv)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SalonAutomobila.Naziv)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Model)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GodinaProizvodnje)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kubikaza)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Boja)
                    </td>
                    <td>
                        <a href="/Automobils/Edit?id=@item.Id&sid=@Model.Id">Izmeni</a> |
                        <a href="/Automobils/Details?id=@item.Id">Detalji</a> |
                        <a href="/Automobils/Delete?id=@item.Id">Obriši</a>

                        @* @Html.ActionLink("Izmeni", "Edit", "Automobils", new { id = item.Id }) |
                            @Html.ActionLink("Detalji", "Details", "Automobils", new { id = item.Id }) |
                            @Html.ActionLink("Obrši", "Delete", "Automobils", new { id = item.Id })*@
                    </td>
                </tr>
            }
        }

    </table>
    <hr />
    <p>
        <a href="/Ugovors/Create?id=@Model.Id">Kreiraj novi ugovor</a>
    </p>
    <h2>Ugovori salona</h2>

    <table class="table">
        <tr>
            <th>
                Proizvođač
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Naziv)
            </th>
            <th></th>
        </tr>
        @if (Model.UgovoriSalona != null)
        {
            foreach (var item in Model.UgovoriSalona)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Proizvodjac.Naziv)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SalonAutomobila.Naziv)
                    </td>
                    <td>
                        <a href="/Ugovors/Edit?id=@item.Id&sid=@Model.Id">Izmeni</a> |
                        <a href="/Ugovors/Details?id=@item.Id">Detalji</a> |
                        <a href="/Ugovors/Delete?id=@item.Id">Obriši</a>


                        @* @Html.ActionLink("Edit", "Edit", "Ugovors", new { id = item.Id }) |
                            @Html.ActionLink("Details", "Details", "Ugovors", new { id = item.Id }) |
                            @Html.ActionLink("Delete", "Delete", "Ugovors", new { id = item.Id })*@
                    </td>
                </tr>
            }
        }
    </table>

</div>



<p>
    @Html.ActionLink("Izmeni", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Nazad na glavni meni", "Index")
</p>

SalonZaAutomobile/Views/SalonAutomobilas/Index.cshtml
@model IEnumerable<SalonZaAutomobile.Models.SalonAutomobila>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Kreiraj novi salon", "Create") | @Html.ActionLink("Idi na automobile", "Index", "Automobils") | @Html.ActionLink("Idi na proizvodjace", "Index", "Proizvodjacs") |
    @Html.ActionLink("Idi na ugovore", "Index", "Ugovors")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Pib)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Drzava)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Adresa)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Pib)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Naziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Drzava)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Adresa)
        </td>
        <td>
            @Html.ActionLink("Izmeni", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Detalji", "Details", new { id=item.Id }) |
            @Html.ActionLink("Obriši", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>